### ISSUE TITLE
Add Binance order fees and no of orders has been made in backtesting mode

### ISSUE THREAD

**Issue by sparkmobi** [markusaksli/TradeBot#42] opened 2022-01-17 08:27 UTC
hello team 

i think that binance takes high fees which will affect the profit number 

can you add total of binance order fees and no. of orders made to get this profit

**Comment by markusaksli** [comment] 2022-01-28 18:07
Duplicate of https://github.com/markusaksli/TradeBot/issues/26

**Closed by markusaksli** 2022-01-28 18:07 UTC
Labels: proposal
